### ISSUE TITLE
drepturi_adaugare_documentatie

### ISSUE THREAD

**Issue by tiulia** [TibiRaducanu/FSJP-GA#1]
as dori sa adaugam un alt articol care pare sa fie interesant. Daca aveti timp putem sa discutam saptamana viitoare. Sunt un pic mai multe detalii despre local search si in plus o varianta pentru optimizari multiobiectiv, NSGA II.

https://www.researchgate.net/profile/Yuan_Yuan73/publication/273171391_Multiobjective_Flexible_Job_Shop_Scheduling_Using_Memetic_Algorithms/links/57e5f17608aedcd5d1a3c417/Multiobjective-Flexible-Job-Shop-Scheduling-Using-Memetic-Algorithms.pdf

De asemenea, pentru implementare GA in python ar putea fi util:
https://github.com/deap/deap
https://deap.readthedocs.io/en/master/

**Comment by TibiRaducanu** [comment]
Super, vorbim saptamana viitoare marti.

mar., 3 dec. 2019, 16:28 Iulia Banu <notifications@github.com> a scris:

**Comment by TibiRaducanu** [comment]
https://github.com/TibiRaducanu/FSJP-GA/invitations

Acesta este link-ul cu invitatia, de asemenea v-am adaugat si la colaboratori.
